### ISSUE TITLE
How to use Hmac in lua-hashing?

### ISSUE THREAD

**Issue by barmaley997** [user-none/lua-hashings#7]
Hello i'am newbie in hashing and cryptographic methods, i very love lua and want to use only it for my needs, now i need to access some authenticated API of some sites through https requests, they demand to use SHA-512 and Hmac methods of hashings in theirs API, i found this library in github, it is clear how to use SHA-256, 512 and others from example of author but i totally cannot understand how to use Hmac method i tried to to so:

local hmacs = require ("hashings.hmac")

local api_secret_key = "My_secret_key";

print(hmacs:new(api_secret_key):new())

but it gives me error:  hmac.lua:38: attempt to get length of a nil value (local 'key')
I totally cannot unerstand!!!!!!!!!!!!!!! PLEASE HELP ME!!!!!!!!!!!!!!!!!!!!!

**Comment by user-none** [comment]
Additional examples have been added to the readme. One of the new examples is generating an HMAC.
